
# encoding: utf-8

# *** GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND ***
#
# Generated from ../LaTeX.g4, derived from latex2sympy
#     latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt
from __future__ import print_function
from antlr4 import *
from io import StringIO
import sys



def serializedATN():
    with StringIO() as buf:
        buf.write(u"\3\u608b\ua72a\u8133\ub9ed\u417c\u3be7\u7786\u5964\2")
        buf.write(u"P\u02de\b\1\4\2\t\2\4\3\t\3\4\4\t\4\4\5\t\5\4\6\t\6\4")
        buf.write(u"\7\t\7\4\b\t\b\4\t\t\t\4\n\t\n\4\13\t\13\4\f\t\f\4\r")
        buf.write(u"\t\r\4\16\t\16\4\17\t\17\4\20\t\20\4\21\t\21\4\22\t\22")
        buf.write(u"\4\23\t\23\4\24\t\24\4\25\t\25\4\26\t\26\4\27\t\27\4")
        buf.write(u"\30\t\30\4\31\t\31\4\32\t\32\4\33\t\33\4\34\t\34\4\35")
        buf.write(u"\t\35\4\36\t\36\4\37\t\37\4 \t \4!\t!\4\"\t\"\4#\t#\4")
        buf.write(u"$\t$\4%\t%\4&\t&\4\'\t\'\4(\t(\4)\t)\4*\t*\4+\t+\4,\t")
        buf.write(u",\4-\t-\4.\t.\4/\t/\4\60\t\60\4\61\t\61\4\62\t\62\4\63")
        buf.write(u"\t\63\4\64\t\64\4\65\t\65\4\66\t\66\4\67\t\67\48\t8\4")
        buf.write(u"9\t9\4:\t:\4;\t;\4<\t<\4=\t=\4>\t>\4?\t?\4@\t@\4A\tA")
        buf.write(u"\4B\tB\4C\tC\4D\tD\4E\tE\4F\tF\4G\tG\4H\tH\4I\tI\4J\t")
        buf.write(u"J\4K\tK\4L\tL\4M\tM\4N\tN\4O\tO\4P\tP\4Q\tQ\3\2\3\2\3")
        buf.write(u"\3\6\3\u00a7\n\3\r\3\16\3\u00a8\3\3\3\3\3\4\3\4\3\4\3")
        buf.write(u"\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\5\4\u00b9\n\4\3\4")
        buf.write(u"\3\4\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\5\5")
        buf.write(u"\u00c8\n\5\3\5\3\5\3\6\3\6\3\6\3\6\3\6\3\6\3\6\3\6\3")
        buf.write(u"\6\3\6\3\6\3\6\3\6\5\6\u00d9\n\6\3\6\3\6\3\7\3\7\3\7")
        buf.write(u"\3\7\3\7\3\7\3\7\3\7\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b")
        buf.write(u"\3\b\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t")
        buf.write(u"\3\t\3\t\3\t\5\t\u00fd\n\t\3\t\3\t\3\n\3\n\3\n\3\n\3")
        buf.write(u"\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\13\3\13")
        buf.write(u"\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3")
        buf.write(u"\13\3\13\3\13\3\13\3\13\3\f\3\f\3\r\3\r\3\16\3\16\3\17")
        buf.write(u"\3\17\3\20\3\20\3\21\3\21\3\22\3\22\3\23\3\23\3\24\3")
        buf.write(u"\24\3\24\3\25\3\25\3\25\3\26\3\26\3\27\3\27\3\30\3\30")
        buf.write(u"\3\30\3\30\3\30\3\30\3\30\3\30\3\31\3\31\3\31\3\31\3")
        buf.write(u"\31\3\31\3\31\3\31\3\31\3\32\3\32\3\33\3\33\3\33\3\33")
        buf.write(u"\3\33\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3")
        buf.write(u"\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34")
        buf.write(u"\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3")
        buf.write(u"\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34")
        buf.write(u"\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3")
        buf.write(u"\34\3\34\3\34\3\34\5\34\u018a\n\34\3\35\3\35\3\35\3\35")
        buf.write(u"\3\35\3\36\3\36\3\36\3\36\3\36\3\37\3\37\3\37\3\37\3")
        buf.write(u"\37\3\37\3 \3 \3 \3 \3 \3!\3!\3!\3!\3!\3\"\3\"\3\"\3")
        buf.write(u"\"\3#\3#\3#\3#\3#\3$\3$\3$\3$\3$\3%\3%\3%\3%\3%\3&\3")
        buf.write(u"&\3&\3&\3&\3\'\3\'\3\'\3\'\3\'\3(\3(\3(\3(\3(\3)\3)\3")
        buf.write(u")\3)\3)\3)\3)\3*\3*\3*\3*\3*\3*\3*\3*\3+\3+\3+\3+\3+")
        buf.write(u"\3+\3+\3+\3,\3,\3,\3,\3,\3,\3,\3-\3-\3-\3-\3-\3-\3-\3")
        buf.write(u".\3.\3.\3.\3.\3.\3.\3.\3/\3/\3/\3/\3/\3/\3/\3/\3\60\3")
        buf.write(u"\60\3\60\3\60\3\60\3\60\3\60\3\60\3\61\3\61\3\61\3\61")
        buf.write(u"\3\61\3\61\3\61\3\61\3\62\3\62\3\62\3\62\3\62\3\62\3")
        buf.write(u"\62\3\62\3\63\3\63\3\63\3\63\3\63\3\63\3\63\3\63\3\64")
        buf.write(u"\3\64\3\64\3\64\3\64\3\64\3\65\3\65\3\65\3\65\3\65\3")
        buf.write(u"\65\3\66\3\66\3\66\3\66\3\66\3\66\3\67\3\67\3\67\3\67")
        buf.write(u"\3\67\3\67\3\67\3\67\38\38\38\38\38\38\38\38\39\39\3")
        buf.write(u"9\39\39\39\39\39\3:\3:\3:\3:\3:\3:\3;\3;\3;\3;\3;\3;")
        buf.write(u"\3;\3<\3<\3<\3<\3<\3<\3=\3=\3=\3=\3=\3>\3>\3>\3>\3>\3")
        buf.write(u">\3?\3?\3?\3?\3?\3?\3?\3@\3@\3@\3@\3@\3@\3@\3@\3A\3A")
        buf.write(u"\3A\3A\3A\3A\3A\3A\3B\3B\3B\3B\3B\3B\3B\3B\3C\3C\3D\3")
        buf.write(u"D\3E\3E\3F\3F\3G\3G\7G\u028e\nG\fG\16G\u0291\13G\3G\3")
        buf.write(u"G\3G\6G\u0296\nG\rG\16G\u0297\5G\u029a\nG\3H\3H\3I\3")
        buf.write(u"I\3J\6J\u02a1\nJ\rJ\16J\u02a2\3J\3J\3J\3J\3J\7J\u02aa")
        buf.write(u"\nJ\fJ\16J\u02ad\13J\3J\7J\u02b0\nJ\fJ\16J\u02b3\13J")
        buf.write(u"\3J\3J\3J\3J\3J\7J\u02ba\nJ\fJ\16J\u02bd\13J\3J\3J\6")
        buf.write(u"J\u02c1\nJ\rJ\16J\u02c2\5J\u02c5\nJ\3K\3K\3L\3L\3M\3")
        buf.write(u"M\3M\3M\3M\3N\3N\3O\3O\3O\3O\3O\3P\3P\3Q\3Q\6Q\u02db")
        buf.write(u"\nQ\rQ\16Q\u02dc\3\u028f\2R\3\3\5\4\7\5\t\6\13\7\r\b")
        buf.write(u"\17\t\21\n\23\13\25\f\27\r\31\16\33\17\35\20\37\21!\22")
        buf.write(u"#\23%\24\'\25)\26+\27-\30/\31\61\32\63\33\65\34\67\35")
        buf.write(u"9\36;\37= ?!A\"C#E$G%I&K\'M(O)Q*S+U,W-Y.[/]\60_\61a\62")
        buf.write(u"c\63e\64g\65i\66k\67m8o9q:s;u<w=y>{?}@\177A\u0081B\u0083")
        buf.write(u"C\u0085D\u0087E\u0089F\u008b\2\u008dG\u008fH\u0091\2")
        buf.write(u"\u0093I\u0095J\u0097K\u0099L\u009bM\u009dN\u009fO\u00a1")
        buf.write(u"P\3\2\5\5\2\13\f\17\17\"\"\4\2C\\c|\3\2\62;\2\u02ee\2")
        buf.write(u"\3\3\2\2\2\2\5\3\2\2\2\2\7\3\2\2\2\2\t\3\2\2\2\2\13\3")
        buf.write(u"\2\2\2\2\r\3\2\2\2\2\17\3\2\2\2\2\21\3\2\2\2\2\23\3\2")
        buf.write(u"\2\2\2\25\3\2\2\2\2\27\3\2\2\2\2\31\3\2\2\2\2\33\3\2")
        buf.write(u"\2\2\2\35\3\2\2\2\2\37\3\2\2\2\2!\3\2\2\2\2#\3\2\2\2")
        buf.write(u"\2%\3\2\2\2\2\'\3\2\2\2\2)\3\2\2\2\2+\3\2\2\2\2-\3\2")
        buf.write(u"\2\2\2/\3\2\2\2\2\61\3\2\2\2\2\63\3\2\2\2\2\65\3\2\2")
        buf.write(u"\2\2\67\3\2\2\2\29\3\2\2\2\2;\3\2\2\2\2=\3\2\2\2\2?\3")
        buf.write(u"\2\2\2\2A\3\2\2\2\2C\3\2\2\2\2E\3\2\2\2\2G\3\2\2\2\2")
        buf.write(u"I\3\2\2\2\2K\3\2\2\2\2M\3\2\2\2\2O\3\2\2\2\2Q\3\2\2\2")
        buf.write(u"\2S\3\2\2\2\2U\3\2\2\2\2W\3\2\2\2\2Y\3\2\2\2\2[\3\2\2")
        buf.write(u"\2\2]\3\2\2\2\2_\3\2\2\2\2a\3\2\2\2\2c\3\2\2\2\2e\3\2")
        buf.write(u"\2\2\2g\3\2\2\2\2i\3\2\2\2\2k\3\2\2\2\2m\3\2\2\2\2o\3")
        buf.write(u"\2\2\2\2q\3\2\2\2\2s\3\2\2\2\2u\3\2\2\2\2w\3\2\2\2\2")
        buf.write(u"y\3\2\2\2\2{\3\2\2\2\2}\3\2\2\2\2\177\3\2\2\2\2\u0081")
        buf.write(u"\3\2\2\2\2\u0083\3\2\2\2\2\u0085\3\2\2\2\2\u0087\3\2")
        buf.write(u"\2\2\2\u0089\3\2\2\2\2\u008d\3\2\2\2\2\u008f\3\2\2\2")
        buf.write(u"\2\u0093\3\2\2\2\2\u0095\3\2\2\2\2\u0097\3\2\2\2\2\u0099")
        buf.write(u"\3\2\2\2\2\u009b\3\2\2\2\2\u009d\3\2\2\2\2\u009f\3\2")
        buf.write(u"\2\2\2\u00a1\3\2\2\2\3\u00a3\3\2\2\2\5\u00a6\3\2\2\2")
        buf.write(u"\7\u00b8\3\2\2\2\t\u00c7\3\2\2\2\13\u00d8\3\2\2\2\r\u00dc")
        buf.write(u"\3\2\2\2\17\u00e4\3\2\2\2\21\u00fc\3\2\2\2\23\u0100\3")
        buf.write(u"\2\2\2\25\u010f\3\2\2\2\27\u0120\3\2\2\2\31\u0122\3\2")
        buf.write(u"\2\2\33\u0124\3\2\2\2\35\u0126\3\2\2\2\37\u0128\3\2\2")
        buf.write(u"\2!\u012a\3\2\2\2#\u012c\3\2\2\2%\u012e\3\2\2\2\'\u0130")
        buf.write(u"\3\2\2\2)\u0133\3\2\2\2+\u0136\3\2\2\2-\u0138\3\2\2\2")
        buf.write(u"/\u013a\3\2\2\2\61\u0142\3\2\2\2\63\u014b\3\2\2\2\65")
        buf.write(u"\u014d\3\2\2\2\67\u0189\3\2\2\29\u018b\3\2\2\2;\u0190")
        buf.write(u"\3\2\2\2=\u0195\3\2\2\2?\u019b\3\2\2\2A\u01a0\3\2\2\2")
        buf.write(u"C\u01a5\3\2\2\2E\u01a9\3\2\2\2G\u01ae\3\2\2\2I\u01b3")
        buf.write(u"\3\2\2\2K\u01b8\3\2\2\2M\u01bd\3\2\2\2O\u01c2\3\2\2\2")
        buf.write(u"Q\u01c7\3\2\2\2S\u01ce\3\2\2\2U\u01d6\3\2\2\2W\u01de")
        buf.write(u"\3\2\2\2Y\u01e5\3\2\2\2[\u01ec\3\2\2\2]\u01f4\3\2\2\2")
        buf.write(u"_\u01fc\3\2\2\2a\u0204\3\2\2\2c\u020c\3\2\2\2e\u0214")
        buf.write(u"\3\2\2\2g\u021c\3\2\2\2i\u0222\3\2\2\2k\u0228\3\2\2\2")
        buf.write(u"m\u022e\3\2\2\2o\u0236\3\2\2\2q\u023e\3\2\2\2s\u0246")
        buf.write(u"\3\2\2\2u\u024c\3\2\2\2w\u0253\3\2\2\2y\u0259\3\2\2\2")
        buf.write(u"{\u025e\3\2\2\2}\u0264\3\2\2\2\177\u026b\3\2\2\2\u0081")
        buf.write(u"\u0273\3\2\2\2\u0083\u027b\3\2\2\2\u0085\u0283\3\2\2")
        buf.write(u"\2\u0087\u0285\3\2\2\2\u0089\u0287\3\2\2\2\u008b\u0289")
        buf.write(u"\3\2\2\2\u008d\u028b\3\2\2\2\u008f\u029b\3\2\2\2\u0091")
        buf.write(u"\u029d\3\2\2\2\u0093\u02c4\3\2\2\2\u0095\u02c6\3\2\2")
        buf.write(u"\2\u0097\u02c8\3\2\2\2\u0099\u02ca\3\2\2\2\u009b\u02cf")
        buf.write(u"\3\2\2\2\u009d\u02d1\3\2\2\2\u009f\u02d6\3\2\2\2\u00a1")
        buf.write(u"\u02d8\3\2\2\2\u00a3\u00a4\7.\2\2\u00a4\4\3\2\2\2\u00a5")
        buf.write(u"\u00a7\t\2\2\2\u00a6\u00a5\3\2\2\2\u00a7\u00a8\3\2\2")
        buf.write(u"\2\u00a8\u00a6\3\2\2\2\u00a8\u00a9\3\2\2\2\u00a9\u00aa")
        buf.write(u"\3\2\2\2\u00aa\u00ab\b\3\2\2\u00ab\6\3\2\2\2\u00ac\u00ad")
        buf.write(u"\7^\2\2\u00ad\u00b9\7.\2\2\u00ae\u00af\7^\2\2\u00af\u00b0")
        buf.write(u"\7v\2\2\u00b0\u00b1\7j\2\2\u00b1\u00b2\7k\2\2\u00b2\u00b3")
        buf.write(u"\7p\2\2\u00b3\u00b4\7u\2\2\u00b4\u00b5\7r\2\2\u00b5\u00b6")
        buf.write(u"\7c\2\2\u00b6\u00b7\7e\2\2\u00b7\u00b9\7g\2\2\u00b8\u00ac")
        buf.write(u"\3\2\2\2\u00b8\u00ae\3\2\2\2\u00b9\u00ba\3\2\2\2\u00ba")
        buf.write(u"\u00bb\b\4\2\2\u00bb\b\3\2\2\2\u00bc\u00bd\7^\2\2\u00bd")
        buf.write(u"\u00c8\7<\2\2\u00be\u00bf\7^\2\2\u00bf\u00c0\7o\2\2\u00c0")
        buf.write(u"\u00c1\7g\2\2\u00c1\u00c2\7f\2\2\u00c2\u00c3\7u\2\2\u00c3")
        buf.write(u"\u00c4\7r\2\2\u00c4\u00c5\7c\2\2\u00c5\u00c6\7e\2\2\u00c6")
        buf.write(u"\u00c8\7g\2\2\u00c7\u00bc\3\2\2\2\u00c7\u00be\3\2\2\2")
        buf.write(u"\u00c8\u00c9\3\2\2\2\u00c9\u00ca\b\5\2\2\u00ca\n\3\2")
        buf.write(u"\2\2\u00cb\u00cc\7^\2\2\u00cc\u00d9\7=\2\2\u00cd\u00ce")
        buf.write(u"\7^\2\2\u00ce\u00cf\7v\2\2\u00cf\u00d0\7j\2\2\u00d0\u00d1")
        buf.write(u"\7k\2\2\u00d1\u00d2\7e\2\2\u00d2\u00d3\7m\2\2\u00d3\u00d4")
        buf.write(u"\7u\2\2\u00d4\u00d5\7r\2\2\u00d5\u00d6\7c\2\2\u00d6\u00d7")
        buf.write(u"\7e\2\2\u00d7\u00d9\7g\2\2\u00d8\u00cb\3\2\2\2\u00d8")
        buf.write(u"\u00cd\3\2\2\2\u00d9\u00da\3\2\2\2\u00da\u00db\b\6\2")
        buf.write(u"\2\u00db\f\3\2\2\2\u00dc\u00dd\7^\2\2\u00dd\u00de\7s")
        buf.write(u"\2\2\u00de\u00df\7w\2\2\u00df\u00e0\7c\2\2\u00e0\u00e1")
        buf.write(u"\7f\2\2\u00e1\u00e2\3\2\2\2\u00e2\u00e3\b\7\2\2\u00e3")
        buf.write(u"\16\3\2\2\2\u00e4\u00e5\7^\2\2\u00e5\u00e6\7s\2\2\u00e6")
        buf.write(u"\u00e7\7s\2\2\u00e7\u00e8\7w\2\2\u00e8\u00e9\7c\2\2\u00e9")
        buf.write(u"\u00ea\7f\2\2\u00ea\u00eb\3\2\2\2\u00eb\u00ec\b\b\2\2")
        buf.write(u"\u00ec\20\3\2\2\2\u00ed\u00ee\7^\2\2\u00ee\u00fd\7#\2")
        buf.write(u"\2\u00ef\u00f0\7^\2\2\u00f0\u00f1\7p\2\2\u00f1\u00f2")
        buf.write(u"\7g\2\2\u00f2\u00f3\7i\2\2\u00f3\u00f4\7v\2\2\u00f4\u00f5")
        buf.write(u"\7j\2\2\u00f5\u00f6\7k\2\2\u00f6\u00f7\7p\2\2\u00f7\u00f8")
        buf.write(u"\7u\2\2\u00f8\u00f9\7r\2\2\u00f9\u00fa\7c\2\2\u00fa\u00fb")
        buf.write(u"\7e\2\2\u00fb\u00fd\7g\2\2\u00fc\u00ed\3\2\2\2\u00fc")
        buf.write(u"\u00ef\3\2\2\2\u00fd\u00fe\3\2\2\2\u00fe\u00ff\b\t\2")
        buf.write(u"\2\u00ff\22\3\2\2\2\u0100\u0101\7^\2\2\u0101\u0102\7")
        buf.write(u"p\2\2\u0102\u0103\7g\2\2\u0103\u0104\7i\2\2\u0104\u0105")
        buf.write(u"\7o\2\2\u0105\u0106\7g\2\2\u0106\u0107\7f\2\2\u0107\u0108")
        buf.write(u"\7u\2\2\u0108\u0109\7r\2\2\u0109\u010a\7c\2\2\u010a\u010b")
        buf.write(u"\7e\2\2\u010b\u010c\7g\2\2\u010c\u010d\3\2\2\2\u010d")
        buf.write(u"\u010e\b\n\2\2\u010e\24\3\2\2\2\u010f\u0110\7^\2\2\u0110")
        buf.write(u"\u0111\7p\2\2\u0111\u0112\7g\2\2\u0112\u0113\7i\2\2\u0113")
        buf.write(u"\u0114\7v\2\2\u0114\u0115\7j\2\2\u0115\u0116\7k\2\2\u0116")
        buf.write(u"\u0117\7e\2\2\u0117\u0118\7m\2\2\u0118\u0119\7u\2\2\u0119")
        buf.write(u"\u011a\7r\2\2\u011a\u011b\7c\2\2\u011b\u011c\7e\2\2\u011c")
        buf.write(u"\u011d\7g\2\2\u011d\u011e\3\2\2\2\u011e\u011f\b\13\2")
        buf.write(u"\2\u011f\26\3\2\2\2\u0120\u0121\7-\2\2\u0121\30\3\2\2")
        buf.write(u"\2\u0122\u0123\7/\2\2\u0123\32\3\2\2\2\u0124\u0125\7")
        buf.write(u",\2\2\u0125\34\3\2\2\2\u0126\u0127\7\61\2\2\u0127\36")
        buf.write(u"\3\2\2\2\u0128\u0129\7*\2\2\u0129 \3\2\2\2\u012a\u012b")
        buf.write(u"\7+\2\2\u012b\"\3\2\2\2\u012c\u012d\7}\2\2\u012d$\3\2")
        buf.write(u"\2\2\u012e\u012f\7\177\2\2\u012f&\3\2\2\2\u0130\u0131")
        buf.write(u"\7^\2\2\u0131\u0132\7}\2\2\u0132(\3\2\2\2\u0133\u0134")
        buf.write(u"\7^\2\2\u0134\u0135\7\177\2\2\u0135*\3\2\2\2\u0136\u0137")
        buf.write(u"\7]\2\2\u0137,\3\2\2\2\u0138\u0139\7_\2\2\u0139.\3\2")
        buf.write(u"\2\2\u013a\u013b\7^\2\2\u013b\u013c\7n\2\2\u013c\u013d")
        buf.write(u"\7g\2\2\u013d\u013e\7h\2\2\u013e\u013f\7v\2\2\u013f\u0140")
        buf.write(u"\3\2\2\2\u0140\u0141\b\30\2\2\u0141\60\3\2\2\2\u0142")
        buf.write(u"\u0143\7^\2\2\u0143\u0144\7t\2\2\u0144\u0145\7k\2\2\u0145")
        buf.write(u"\u0146\7i\2\2\u0146\u0147\7j\2\2\u0147\u0148\7v\2\2\u0148")
        buf.write(u"\u0149\3\2\2\2\u0149\u014a\b\31\2\2\u014a\62\3\2\2\2")
        buf.write(u"\u014b\u014c\7~\2\2\u014c\64\3\2\2\2\u014d\u014e\7^\2")
        buf.write(u"\2\u014e\u014f\7n\2\2\u014f\u0150\7k\2\2\u0150\u0151")
        buf.write(u"\7o\2\2\u0151\66\3\2\2\2\u0152\u0153\7^\2\2\u0153\u0154")
        buf.write(u"\7v\2\2\u0154\u018a\7q\2\2\u0155\u0156\7^\2\2\u0156\u0157")
        buf.write(u"\7t\2\2\u0157\u0158\7k\2\2\u0158\u0159\7i\2\2\u0159\u015a")
        buf.write(u"\7j\2\2\u015a\u015b\7v\2\2\u015b\u015c\7c\2\2\u015c\u015d")
        buf.write(u"\7t\2\2\u015d\u015e\7t\2\2\u015e\u015f\7q\2\2\u015f\u018a")
        buf.write(u"\7y\2\2\u0160\u0161\7^\2\2\u0161\u0162\7T\2\2\u0162\u0163")
        buf.write(u"\7k\2\2\u0163\u0164\7i\2\2\u0164\u0165\7j\2\2\u0165\u0166")
        buf.write(u"\7v\2\2\u0166\u0167\7c\2\2\u0167\u0168\7t\2\2\u0168\u0169")
        buf.write(u"\7t\2\2\u0169\u016a\7q\2\2\u016a\u018a\7y\2\2\u016b\u016c")
        buf.write(u"\7^\2\2\u016c\u016d\7n\2\2\u016d\u016e\7q\2\2\u016e\u016f")
        buf.write(u"\7p\2\2\u016f\u0170\7i\2\2\u0170\u0171\7t\2\2\u0171\u0172")
        buf.write(u"\7k\2\2\u0172\u0173\7i\2\2\u0173\u0174\7j\2\2\u0174\u0175")
        buf.write(u"\7v\2\2\u0175\u0176\7c\2\2\u0176\u0177\7t\2\2\u0177\u0178")
        buf.write(u"\7t\2\2\u0178\u0179\7q\2\2\u0179\u018a\7y\2\2\u017a\u017b")
        buf.write(u"\7^\2\2\u017b\u017c\7N\2\2\u017c\u017d\7q\2\2\u017d\u017e")
        buf.write(u"\7p\2\2\u017e\u017f\7i\2\2\u017f\u0180\7t\2\2\u0180\u0181")
        buf.write(u"\7k\2\2\u0181\u0182\7i\2\2\u0182\u0183\7j\2\2\u0183\u0184")
        buf.write(u"\7v\2\2\u0184\u0185\7c\2\2\u0185\u0186\7t\2\2\u0186\u0187")
        buf.write(u"\7t\2\2\u0187\u0188\7q\2\2\u0188\u018a\7y\2\2\u0189\u0152")
        buf.write(u"\3\2\2\2\u0189\u0155\3\2\2\2\u0189\u0160\3\2\2\2\u0189")
        buf.write(u"\u016b\3\2\2\2\u0189\u017a\3\2\2\2\u018a8\3\2\2\2\u018b")
        buf.write(u"\u018c\7^\2\2\u018c\u018d\7k\2\2\u018d\u018e\7p\2\2\u018e")
        buf.write(u"\u018f\7v\2\2\u018f:\3\2\2\2\u0190\u0191\7^\2\2\u0191")
        buf.write(u"\u0192\7u\2\2\u0192\u0193\7w\2\2\u0193\u0194\7o\2\2\u0194")
        buf.write(u"<\3\2\2\2\u0195\u0196\7^\2\2\u0196\u0197\7r\2\2\u0197")
        buf.write(u"\u0198\7t\2\2\u0198\u0199\7q\2\2\u0199\u019a\7f\2\2\u019a")
        buf.write(u">\3\2\2\2\u019b\u019c\7^\2\2\u019c\u019d\7g\2\2\u019d")
        buf.write(u"\u019e\7z\2\2\u019e\u019f\7r\2\2\u019f@\3\2\2\2\u01a0")
        buf.write(u"\u01a1\7^\2\2\u01a1\u01a2\7n\2\2\u01a2\u01a3\7q\2\2\u01a3")
        buf.write(u"\u01a4\7i\2\2\u01a4B\3\2\2\2\u01a5\u01a6\7^\2\2\u01a6")
        buf.write(u"\u01a7\7n\2\2\u01a7\u01a8\7p\2\2\u01a8D\3\2\2\2\u01a9")
        buf.write(u"\u01aa\7^\2\2\u01aa\u01ab\7u\2\2\u01ab\u01ac\7k\2\2\u01ac")
        buf.write(u"\u01ad\7p\2\2\u01adF\3\2\2\2\u01ae\u01af\7^\2\2\u01af")
        buf.write(u"\u01b0\7e\2\2\u01b0\u01b1\7q\2\2\u01b1\u01b2\7u\2\2\u01b2")
        buf.write(u"H\3\2\2\2\u01b3\u01b4\7^\2\2\u01b4\u01b5\7v\2\2\u01b5")
        buf.write(u"\u01b6\7c\2\2\u01b6\u01b7\7p\2\2\u01b7J\3\2\2\2\u01b8")
        buf.write(u"\u01b9\7^\2\2\u01b9\u01ba\7e\2\2\u01ba\u01bb\7u\2\2\u01bb")
        buf.write(u"\u01bc\7e\2\2\u01bcL\3\2\2\2\u01bd\u01be\7^\2\2\u01be")
        buf.write(u"\u01bf\7u\2\2\u01bf\u01c0\7g\2\2\u01c0\u01c1\7e\2\2\u01c1")
        buf.write(u"N\3\2\2\2\u01c2\u01c3\7^\2\2\u01c3\u01c4\7e\2\2\u01c4")
        buf.write(u"\u01c5\7q\2\2\u01c5\u01c6\7v\2\2\u01c6P\3\2\2\2\u01c7")
        buf.write(u"\u01c8\7^\2\2\u01c8\u01c9\7I\2\2\u01c9\u01ca\7c\2\2\u01ca")
        buf.write(u"\u01cb\7o\2\2\u01cb\u01cc\7o\2\2\u01cc\u01cd\7c\2\2\u01cd")
        buf.write(u"R\3\2\2\2\u01ce\u01cf\7^\2\2\u01cf\u01d0\7n\2\2\u01d0")
        buf.write(u"\u01d1\7h\2\2\u01d1\u01d2\7n\2\2\u01d2\u01d3\7q\2\2\u01d3")
        buf.write(u"\u01d4\7q\2\2\u01d4\u01d5\7t\2\2\u01d5T\3\2\2\2\u01d6")
        buf.write(u"\u01d7\7^\2\2\u01d7\u01d8\7t\2\2\u01d8\u01d9\7h\2\2\u01d9")
        buf.write(u"\u01da\7n\2\2\u01da\u01db\7q\2\2\u01db\u01dc\7q\2\2\u01dc")
        buf.write(u"\u01dd\7t\2\2\u01ddV\3\2\2\2\u01de\u01df\7^\2\2\u01df")
        buf.write(u"\u01e0\7n\2\2\u01e0\u01e1\7e\2\2\u01e1\u01e2\7g\2\2\u01e2")
        buf.write(u"\u01e3\7k\2\2\u01e3\u01e4\7n\2\2\u01e4X\3\2\2\2\u01e5")
        buf.write(u"\u01e6\7^\2\2\u01e6\u01e7\7t\2\2\u01e7\u01e8\7e\2\2\u01e8")
        buf.write(u"\u01e9\7g\2\2\u01e9\u01ea\7k\2\2\u01ea\u01eb\7n\2\2\u01eb")
        buf.write(u"Z\3\2\2\2\u01ec\u01ed\7^\2\2\u01ed\u01ee\7c\2\2\u01ee")
        buf.write(u"\u01ef\7t\2\2\u01ef\u01f0\7e\2\2\u01f0\u01f1\7u\2\2\u01f1")
        buf.write(u"\u01f2\7k\2\2\u01f2\u01f3\7p\2\2\u01f3\\\3\2\2\2\u01f4")
        buf.write(u"\u01f5\7^\2\2\u01f5\u01f6\7c\2\2\u01f6\u01f7\7t\2\2\u01f7")
        buf.write(u"\u01f8\7e\2\2\u01f8\u01f9\7e\2\2\u01f9\u01fa\7q\2\2\u01fa")
        buf.write(u"\u01fb\7u\2\2\u01fb^\3\2\2\2\u01fc\u01fd\7^\2\2\u01fd")
        buf.write(u"\u01fe\7c\2\2\u01fe\u01ff\7t\2\2\u01ff\u0200\7e\2\2\u0200")
        buf.write(u"\u0201\7v\2\2\u0201\u0202\7c\2\2\u0202\u0203\7p\2\2\u0203")
        buf.write(u"`\3\2\2\2\u0204\u0205\7^\2\2\u0205\u0206\7c\2\2\u0206")
        buf.write(u"\u0207\7t\2\2\u0207\u0208\7e\2\2\u0208\u0209\7e\2\2\u0209")
        buf.write(u"\u020a\7u\2\2\u020a\u020b\7e\2\2\u020bb\3\2\2\2\u020c")
        buf.write(u"\u020d\7^\2\2\u020d\u020e\7c\2\2\u020e\u020f\7t\2\2\u020f")
        buf.write(u"\u0210\7e\2\2\u0210\u0211\7u\2\2\u0211\u0212\7g\2\2\u0212")
        buf.write(u"\u0213\7e\2\2\u0213d\3\2\2\2\u0214\u0215\7^\2\2\u0215")
        buf.write(u"\u0216\7c\2\2\u0216\u0217\7t\2\2\u0217\u0218\7e\2\2\u0218")
        buf.write(u"\u0219\7e\2\2\u0219\u021a\7q\2\2\u021a\u021b\7v\2\2\u021b")
        buf.write(u"f\3\2\2\2\u021c\u021d\7^\2\2\u021d\u021e\7u\2\2\u021e")
        buf.write(u"\u021f\7k\2\2\u021f\u0220\7p\2\2\u0220\u0221\7j\2\2\u0221")
        buf.write(u"h\3\2\2\2\u0222\u0223\7^\2\2\u0223\u0224\7e\2\2\u0224")
        buf.write(u"\u0225\7q\2\2\u0225\u0226\7u\2\2\u0226\u0227\7j\2\2\u0227")
        buf.write(u"j\3\2\2\2\u0228\u0229\7^\2\2\u0229\u022a\7v\2\2\u022a")
        buf.write(u"\u022b\7c\2\2\u022b\u022c\7p\2\2\u022c\u022d\7j\2\2\u022d")
        buf.write(u"l\3\2\2\2\u022e\u022f\7^\2\2\u022f\u0230\7c\2\2\u0230")
        buf.write(u"\u0231\7t\2\2\u0231\u0232\7u\2\2\u0232\u0233\7k\2\2\u0233")
        buf.write(u"\u0234\7p\2\2\u0234\u0235\7j\2\2\u0235n\3\2\2\2\u0236")
        buf.write(u"\u0237\7^\2\2\u0237\u0238\7c\2\2\u0238\u0239\7t\2\2\u0239")
        buf.write(u"\u023a\7e\2\2\u023a\u023b\7q\2\2\u023b\u023c\7u\2\2\u023c")
        buf.write(u"\u023d\7j\2\2\u023dp\3\2\2\2\u023e\u023f\7^\2\2\u023f")
        buf.write(u"\u0240\7c\2\2\u0240\u0241\7t\2\2\u0241\u0242\7v\2\2\u0242")
        buf.write(u"\u0243\7c\2\2\u0243\u0244\7p\2\2\u0244\u0245\7j\2\2\u0245")
        buf.write(u"r\3\2\2\2\u0246\u0247\7^\2\2\u0247\u0248\7u\2\2\u0248")
        buf.write(u"\u0249\7s\2\2\u0249\u024a\7t\2\2\u024a\u024b\7v\2\2\u024b")
        buf.write(u"t\3\2\2\2\u024c\u024d\7^\2\2\u024d\u024e\7v\2\2\u024e")
        buf.write(u"\u024f\7k\2\2\u024f\u0250\7o\2\2\u0250\u0251\7g\2\2\u0251")
        buf.write(u"\u0252\7u\2\2\u0252v\3\2\2\2\u0253\u0254\7^\2\2\u0254")
        buf.write(u"\u0255\7e\2\2\u0255\u0256\7f\2\2\u0256\u0257\7q\2\2\u0257")
        buf.write(u"\u0258\7v\2\2\u0258x\3\2\2\2\u0259\u025a\7^\2\2\u025a")
        buf.write(u"\u025b\7f\2\2\u025b\u025c\7k\2\2\u025c\u025d\7x\2\2\u025d")
        buf.write(u"z\3\2\2\2\u025e\u025f\7^\2\2\u025f\u0260\7h\2\2\u0260")
        buf.write(u"\u0261\7t\2\2\u0261\u0262\7c\2\2\u0262\u0263\7e\2\2\u0263")
        buf.write(u"|\3\2\2\2\u0264\u0265\7^\2\2\u0265\u0266\7d\2\2\u0266")
        buf.write(u"\u0267\7k\2\2\u0267\u0268\7p\2\2\u0268\u0269\7q\2\2\u0269")
        buf.write(u"\u026a\7o\2\2\u026a~\3\2\2\2\u026b\u026c\7^\2\2\u026c")
        buf.write(u"\u026d\7f\2\2\u026d\u026e\7d\2\2\u026e\u026f\7k\2\2\u026f")
        buf.write(u"\u0270\7p\2\2\u0270\u0271\7q\2\2\u0271\u0272\7o\2\2\u0272")
        buf.write(u"\u0080\3\2\2\2\u0273\u0274\7^\2\2\u0274\u0275\7v\2\2")
        buf.write(u"\u0275\u0276\7d\2\2\u0276\u0277\7k\2\2\u0277\u0278\7")
        buf.write(u"p\2\2\u0278\u0279\7q\2\2\u0279\u027a\7o\2\2\u027a\u0082")
        buf.write(u"\3\2\2\2\u027b\u027c\7^\2\2\u027c\u027d\7o\2\2\u027d")
        buf.write(u"\u027e\7c\2\2\u027e\u027f\7v\2\2\u027f\u0280\7j\2\2\u0280")
        buf.write(u"\u0281\7k\2\2\u0281\u0282\7v\2\2\u0282\u0084\3\2\2\2")
        buf.write(u"\u0283\u0284\7a\2\2\u0284\u0086\3\2\2\2\u0285\u0286\7")
        buf.write(u"`\2\2\u0286\u0088\3\2\2\2\u0287\u0288\7<\2\2\u0288\u008a")
        buf.write(u"\3\2\2\2\u0289\u028a\t\2\2\2\u028a\u008c\3\2\2\2\u028b")
        buf.write(u"\u028f\7f\2\2\u028c\u028e\5\u008bF\2\u028d\u028c\3\2")
        buf.write(u"\2\2\u028e\u0291\3\2\2\2\u028f\u0290\3\2\2\2\u028f\u028d")
        buf.write(u"\3\2\2\2\u0290\u0299\3\2\2\2\u0291\u028f\3\2\2\2\u0292")
        buf.write(u"\u029a\t\3\2\2\u0293\u0295\7^\2\2\u0294\u0296\t\3\2\2")
        buf.write(u"\u0295\u0294\3\2\2\2\u0296\u0297\3\2\2\2\u0297\u0295")
        buf.write(u"\3\2\2\2\u0297\u0298\3\2\2\2\u0298\u029a\3\2\2\2\u0299")
        buf.write(u"\u0292\3\2\2\2\u0299\u0293\3\2\2\2\u029a\u008e\3\2\2")
        buf.write(u"\2\u029b\u029c\t\3\2\2\u029c\u0090\3\2\2\2\u029d\u029e")
        buf.write(u"\t\4\2\2\u029e\u0092\3\2\2\2\u029f\u02a1\5\u0091I\2\u02a0")
        buf.write(u"\u029f\3\2\2\2\u02a1\u02a2\3\2\2\2\u02a2\u02a0\3\2\2")
        buf.write(u"\2\u02a2\u02a3\3\2\2\2\u02a3\u02ab\3\2\2\2\u02a4\u02a5")
        buf.write(u"\7.\2\2\u02a5\u02a6\5\u0091I\2\u02a6\u02a7\5\u0091I\2")
        buf.write(u"\u02a7\u02a8\5\u0091I\2\u02a8\u02aa\3\2\2\2\u02a9\u02a4")
        buf.write(u"\3\2\2\2\u02aa\u02ad\3\2\2\2\u02ab\u02a9\3\2\2\2\u02ab")
        buf.write(u"\u02ac\3\2\2\2\u02ac\u02c5\3\2\2\2\u02ad\u02ab\3\2\2")
        buf.write(u"\2\u02ae\u02b0\5\u0091I\2\u02af\u02ae\3\2\2\2\u02b0\u02b3")
        buf.write(u"\3\2\2\2\u02b1\u02af\3\2\2\2\u02b1\u02b2\3\2\2\2\u02b2")
        buf.write(u"\u02bb\3\2\2\2\u02b3\u02b1\3\2\2\2\u02b4\u02b5\7.\2\2")
        buf.write(u"\u02b5\u02b6\5\u0091I\2\u02b6\u02b7\5\u0091I\2\u02b7")
        buf.write(u"\u02b8\5\u0091I\2\u02b8\u02ba\3\2\2\2\u02b9\u02b4\3\2")
        buf.write(u"\2\2\u02ba\u02bd\3\2\2\2\u02bb\u02b9\3\2\2\2\u02bb\u02bc")
        buf.write(u"\3\2\2\2\u02bc\u02be\3\2\2\2\u02bd\u02bb\3\2\2\2\u02be")
        buf.write(u"\u02c0\7\60\2\2\u02bf\u02c1\5\u0091I\2\u02c0\u02bf\3")
        buf.write(u"\2\2\2\u02c1\u02c2\3\2\2\2\u02c2\u02c0\3\2\2\2\u02c2")
        buf.write(u"\u02c3\3\2\2\2\u02c3\u02c5\3\2\2\2\u02c4\u02a0\3\2\2")
        buf.write(u"\2\u02c4\u02b1\3\2\2\2\u02c5\u0094\3\2\2\2\u02c6\u02c7")
        buf.write(u"\7?\2\2\u02c7\u0096\3\2\2\2\u02c8\u02c9\7>\2\2\u02c9")
        buf.write(u"\u0098\3\2\2\2\u02ca\u02cb\7^\2\2\u02cb\u02cc\7n\2\2")
        buf.write(u"\u02cc\u02cd\7g\2\2\u02cd\u02ce\7s\2\2\u02ce\u009a\3")
        buf.write(u"\2\2\2\u02cf\u02d0\7@\2\2\u02d0\u009c\3\2\2\2\u02d1\u02d2")
        buf.write(u"\7^\2\2\u02d2\u02d3\7i\2\2\u02d3\u02d4\7g\2\2\u02d4\u02d5")
        buf.write(u"\7s\2\2\u02d5\u009e\3\2\2\2\u02d6\u02d7\7#\2\2\u02d7")
        buf.write(u"\u00a0\3\2\2\2\u02d8\u02da\7^\2\2\u02d9\u02db\t\3\2\2")
        buf.write(u"\u02da\u02d9\3\2\2\2\u02db\u02dc\3\2\2\2\u02dc\u02da")
        buf.write(u"\3\2\2\2\u02dc\u02dd\3\2\2\2\u02dd\u00a2\3\2\2\2\23\2")
        buf.write(u"\u00a8\u00b8\u00c7\u00d8\u00fc\u0189\u028f\u0297\u0299")
        buf.write(u"\u02a2\u02ab\u02b1\u02bb\u02c2\u02c4\u02dc\3\b\2\2")
        return buf.getvalue()


class LaTeXLexer(Lexer):

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [ DFA(ds, i) for i, ds in enumerate(atn.decisionToState) ]

    T__0 = 1
    WS = 2
    THINSPACE = 3
    MEDSPACE = 4
    THICKSPACE = 5
    QUAD = 6
    QQUAD = 7
    NEGTHINSPACE = 8
    NEGMEDSPACE = 9
    NEGTHICKSPACE = 10
    ADD = 11
    SUB = 12
    MUL = 13
    DIV = 14
    L_PAREN = 15
    R_PAREN = 16
    L_BRACE = 17
    R_BRACE = 18
    L_BRACE_LITERAL = 19
    R_BRACE_LITERAL = 20
    L_BRACKET = 21
    R_BRACKET = 22
    CMD_LEFT = 23
    CMD_RIGHT = 24
    BAR = 25
    FUNC_LIM = 26
    LIM_APPROACH_SYM = 27
    FUNC_INT = 28
    FUNC_SUM = 29
    FUNC_PROD = 30
    FUNC_EXP = 31
    FUNC_LOG = 32
    FUNC_LN = 33
    FUNC_SIN = 34
    FUNC_COS = 35
    FUNC_TAN = 36
    FUNC_CSC = 37
    FUNC_SEC = 38
    FUNC_COT = 39
    FUNC_GAMMA = 40
    L_FLOOR = 41
    R_FLOOR = 42
    L_CEIL = 43
    R_CEIL = 44
    FUNC_ARCSIN = 45
    FUNC_ARCCOS = 46
    FUNC_ARCTAN = 47
    FUNC_ARCCSC = 48
    FUNC_ARCSEC = 49
    FUNC_ARCCOT = 50
    FUNC_SINH = 51
    FUNC_COSH = 52
    FUNC_TANH = 53
    FUNC_ARSINH = 54
    FUNC_ARCOSH = 55
    FUNC_ARTANH = 56
    FUNC_SQRT = 57
    CMD_TIMES = 58
    CMD_CDOT = 59
    CMD_DIV = 60
    CMD_FRAC = 61
    CMD_BINOM = 62
    CMD_DBINOM = 63
    CMD_TBINOM = 64
    CMD_MATHIT = 65
    UNDERSCORE = 66
    CARET = 67
    COLON = 68
    DIFFERENTIAL = 69
    LETTER = 70
    NUMBER = 71
    EQUAL = 72
    LT = 73
    LTE = 74
    GT = 75
    GTE = 76
    BANG = 77
    SYMBOL = 78

    channelNames = [ u"DEFAULT_TOKEN_CHANNEL", u"HIDDEN" ]

    modeNames = [ u"DEFAULT_MODE" ]

    literalNames = [ u"<INVALID>",
            u"','", u"'\\quad'", u"'\\qquad'", u"'\\negmedspace'", u"'\\negthickspace'",
            u"'+'", u"'-'", u"'*'", u"'/'", u"'('", u"')'", u"'{'", u"'}'",
            u"'\\{'", u"'\\}'", u"'['", u"']'", u"'\\left'", u"'\\right'",
            u"'|'", u"'\\lim'", u"'\\int'", u"'\\sum'", u"'\\prod'", u"'\\exp'",
            u"'\\log'", u"'\\ln'", u"'\\sin'", u"'\\cos'", u"'\\tan'", u"'\\csc'",
            u"'\\sec'", u"'\\cot'", u"'\\Gamma'", u"'\\lfloor'", u"'\\rfloor'",
            u"'\\lceil'", u"'\\rceil'", u"'\\arcsin'", u"'\\arccos'", u"'\\arctan'",
            u"'\\arccsc'", u"'\\arcsec'", u"'\\arccot'", u"'\\sinh'", u"'\\cosh'",
            u"'\\tanh'", u"'\\arsinh'", u"'\\arcosh'", u"'\\artanh'", u"'\\sqrt'",
            u"'\\times'", u"'\\cdot'", u"'\\div'", u"'\\frac'", u"'\\binom'",
            u"'\\dbinom'", u"'\\tbinom'", u"'\\mathit'", u"'_'", u"'^'",
            u"':'", u"'='", u"'<'", u"'\\leq'", u"'>'", u"'\\geq'", u"'!'" ]

    symbolicNames = [ u"<INVALID>",
            u"WS", u"THINSPACE", u"MEDSPACE", u"THICKSPACE", u"QUAD", u"QQUAD",
            u"NEGTHINSPACE", u"NEGMEDSPACE", u"NEGTHICKSPACE", u"ADD", u"SUB",
            u"MUL", u"DIV", u"L_PAREN", u"R_PAREN", u"L_BRACE", u"R_BRACE",
            u"L_BRACE_LITERAL", u"R_BRACE_LITERAL", u"L_BRACKET", u"R_BRACKET",
            u"CMD_LEFT", u"CMD_RIGHT", u"BAR", u"FUNC_LIM", u"LIM_APPROACH_SYM",
            u"FUNC_INT", u"FUNC_SUM", u"FUNC_PROD", u"FUNC_EXP", u"FUNC_LOG",
            u"FUNC_LN", u"FUNC_SIN", u"FUNC_COS", u"FUNC_TAN", u"FUNC_CSC",
            u"FUNC_SEC", u"FUNC_COT", u"FUNC_GAMMA", u"L_FLOOR", u"R_FLOOR",
            u"L_CEIL", u"R_CEIL", u"FUNC_ARCSIN", u"FUNC_ARCCOS", u"FUNC_ARCTAN",
            u"FUNC_ARCCSC", u"FUNC_ARCSEC", u"FUNC_ARCCOT", u"FUNC_SINH",
            u"FUNC_COSH", u"FUNC_TANH", u"FUNC_ARSINH", u"FUNC_ARCOSH",
            u"FUNC_ARTANH", u"FUNC_SQRT", u"CMD_TIMES", u"CMD_CDOT", u"CMD_DIV",
            u"CMD_FRAC", u"CMD_BINOM", u"CMD_DBINOM", u"CMD_TBINOM", u"CMD_MATHIT",
            u"UNDERSCORE", u"CARET", u"COLON", u"DIFFERENTIAL", u"LETTER",
            u"NUMBER", u"EQUAL", u"LT", u"LTE", u"GT", u"GTE", u"BANG",
            u"SYMBOL" ]

    ruleNames = [ u"T__0", u"WS", u"THINSPACE", u"MEDSPACE", u"THICKSPACE",
                  u"QUAD", u"QQUAD", u"NEGTHINSPACE", u"NEGMEDSPACE", u"NEGTHICKSPACE",
                  u"ADD", u"SUB", u"MUL", u"DIV", u"L_PAREN", u"R_PAREN",
                  u"L_BRACE", u"R_BRACE", u"L_BRACE_LITERAL", u"R_BRACE_LITERAL",
                  u"L_BRACKET", u"R_BRACKET", u"CMD_LEFT", u"CMD_RIGHT",
                  u"BAR", u"FUNC_LIM", u"LIM_APPROACH_SYM", u"FUNC_INT",
                  u"FUNC_SUM", u"FUNC_PROD", u"FUNC_EXP", u"FUNC_LOG", u"FUNC_LN",
                  u"FUNC_SIN", u"FUNC_COS", u"FUNC_TAN", u"FUNC_CSC", u"FUNC_SEC",
                  u"FUNC_COT", u"FUNC_GAMMA", u"L_FLOOR", u"R_FLOOR", u"L_CEIL",
                  u"R_CEIL", u"FUNC_ARCSIN", u"FUNC_ARCCOS", u"FUNC_ARCTAN",
                  u"FUNC_ARCCSC", u"FUNC_ARCSEC", u"FUNC_ARCCOT", u"FUNC_SINH",
                  u"FUNC_COSH", u"FUNC_TANH", u"FUNC_ARSINH", u"FUNC_ARCOSH",
                  u"FUNC_ARTANH", u"FUNC_SQRT", u"CMD_TIMES", u"CMD_CDOT",
                  u"CMD_DIV", u"CMD_FRAC", u"CMD_BINOM", u"CMD_DBINOM",
                  u"CMD_TBINOM", u"CMD_MATHIT", u"UNDERSCORE", u"CARET",
                  u"COLON", u"WS_CHAR", u"DIFFERENTIAL", u"LETTER", u"DIGIT",
                  u"NUMBER", u"EQUAL", u"LT", u"LTE", u"GT", u"GTE", u"BANG",
                  u"SYMBOL" ]

    grammarFileName = u"LaTeX.g4"

    def __init__(self, input=None, output=sys.stdout):
        super(LaTeXLexer, self).__init__(input, output=output)
        self.checkVersion("4.7.2")
        self._interp = LexerATNSimulator(self, self.atn, self.decisionsToDFA, PredictionContextCache())
        self._actions = None
        self._predicates = None


